
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-claim-tmax-io-v1alpha1-clusterclaim
  failurePolicy: Fail
  name: mutation.webhook.clusterclaim
  rules:
  - apiGroups:
    - claim.tmax.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - clusterclaims
  sideEffects: NoneOnDryRun

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-claim-tmax-io-v1alpha1-clusterclaim
  failurePolicy: Fail
  name: validation.webhook.clusterclaim
  rules:
  - apiGroups:
    - claim.tmax.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - clusterclaims
    - clusterclaims/status
  sideEffects: NoneOnDryRun
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cluster-tmax-io-v1alpha1-clustermanager
  failurePolicy: Fail
  name: validation.webhook.clustermanager
  rules:
  - apiGroups:
    - cluster.tmax.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - clustermanagers
  sideEffects: NoneOnDryRun
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cluster-tmax-io-v1alpha1-clusterregistration
  failurePolicy: Fail
  name: validation.webhook.clusterregistration
  rules:
  - apiGroups:
    - cluster.tmax.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - clusterregistrations
  sideEffects: NoneOnDryRun
