# permissions for end users to view clusterupdateclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterupdateclaim-viewer-role
rules:
- apiGroups:
  - claim.tmax.io
  resources:
  - clusterupdateclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - claim.tmax.io
  resources:
  - clusterupdateclaims/status
  verbs:
  - get
